

#deployment details for loading deakin-library image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: task7sit722part3.azurecr.io/library:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: "postgresql://part3db_user:Blg8mL9EaYVh0zAit8vk9LslShOnGOFp@dpg-crff4argbbvc73c3n5ng-a.oregon-postgres.render.com/part3db"
---
apiVersion: v1
kind: Service
metadata:
  name: library
spec:
  selector:
    app: library
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 8002


---
#deployment details for loading deakin-library image (book_catalog)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: task7sit722part3.azurecr.io/inventory:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          value: "postgresql://part3db_user:Blg8mL9EaYVh0zAit8vk9LslShOnGOFp@dpg-crff4argbbvc73c3n5ng-a.oregon-postgres.render.com/part3db"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
    app: inventory
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 8003
